[package]
name = "rish"
version = "0.0.1"
edition = "2021"
authors = ["valkyrie_pilot <valk@randomairborne.dev>"]
license = "Apache-2.0"


[dependencies]
rustyline = "9.1"
rustyline-derive = "0.6"
toml = "0.5"
serde = "1.0"
serde_derive = "1.0"

